# Applying Machine Learning for classification and prediction using the dataset.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

customers = pd.read_csv("final_dataset/customers.csv")
order_items = pd.read_csv("final_dataset/order_items.csv")
orders = pd.read_csv("final_dataset/orders.csv")
payments = pd.read_csv("final_dataset/payments.csv")
products = pd.read_csv("final_dataset/products.csv")
reviews = pd.read_csv("final_dataset/reviews.csv")
sellers = pd.read_csv("final_dataset/sellers.csv")

In [2]:
# Converting object to DateTime format.

orders['order_purchase_date'] =  pd.to_datetime(orders['order_purchase_date'], format="%d-%m-%Y %H:%M")
orders['order_approved_date'] =  pd.to_datetime(orders['order_approved_date'], format="%d-%m-%Y %H:%M")
orders['order_delivered_carrier_date'] =  pd.to_datetime(orders['order_delivered_carrier_date'], format="%d-%m-%Y %H:%M")
orders['order_delivered_customer_date'] =  pd.to_datetime(orders['order_delivered_customer_date'], format="%d-%m-%Y %H:%M")
orders['order_estimated_delivery_date'] =  pd.to_datetime(orders['order_estimated_delivery_date'], format="%d-%m-%Y %H:%M")

### Predicting the fault of logistic partner in late delivery of order.

In [38]:
late = orders[orders.order_delivered_customer_date > orders.order_estimated_delivery_date]
late['fault'] = 0
late.fault[late.order_delivered_carrier_date > late.order_estimated_delivery_date] = 'seller'
late.fault[late.order_delivered_carrier_date <= late.order_estimated_delivery_date] = 'logistic partner'
late.drop(late.loc[late['fault']==0].index, inplace=True)
late

C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['fault'] = 0
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.order_delivered_carrier_date > late.order_estimated_delivery_date] = 'seller'
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.order_delivered_carrier_date > late.order_estimated_delivery_date] = 'seller'
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.order_delivered_carrier_date <= late.order_estimated_delivery_date] = 'logistic partner'
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.order_delivered_carrier_date <= late.order_estimated_delivery_date] = 'logistic partner'
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3283611505.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.drop(late.loc[late['fault']==0].index, inplace=True)

,order_id,customer_id,order_status,order_purchase_date,order_approved_date,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,fault
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:00,2017-09-19 04:04:00,2017-10-06 17:50:00,2017-10-09 22:23:00,2017-09-28,seller
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:00,2018-02-22 02:30:00,2018-02-26 22:25:00,2018-03-21 22:03:00,2018-03-12,logistic partner
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:00,2018-02-17 16:15:00,2018-02-20 23:03:00,2018-03-20 00:59:00,2018-03-20,logistic partner
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:00,2017-11-25 00:21:00,2017-12-13 21:14:00,2017-12-28 18:59:00,2017-12-21,logistic partner
57,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:00,2018-03-09 15:40:00,2018-03-15 00:31:00,2018-04-03 13:28:00,2018-04-02,logistic partner
...,...,...,...,...,...,...,...,...,...
99396,b3112ca67f3afd4e20cf2ee91fc4f804,6f83c71b6c044fb156d697d4130fe9b5,delivered,2018-08-02 22:46:00,2018-08-02 23:04:00,2018-08-15 17:42:00,2018-08-21 00:03:00,2018-08-16,logistic partner
99397,0fa1fab1d7c1211c824596ed5e111e3c,7f3bd6c94d2daf7b6462d1a894a775b4,delivered,2018-03-13 21:48:00,2018-03-13 22:40:00,2018-03-14 19:27:00,2018-04-05 19:59:00,2018-04-02,logistic partner
99423,38e9133ce29f6bbe35aed9c3863dce01,ad312389a098ceff46ce92c4595c06d0,delivered,2017-10-12 20:54:00,2017-10-14 03:28:00,2017-10-17 17:04:00,2017-11-21 17:06:00,2017-10-31,logistic partner
99425,d692ef54145c9cb3322ec2e5508aa3f4,82ddfcf9438b0cd1117b55ac33184df8,delivered,2018-03-21 19:47:00,2018-03-21 20:05:00,2018-03-22 21:11:00,2018-04-11 00:48:00,2018-04-09,logistic partner
99432,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:00,2017-12-20 10:09:00,2017-12-20 20:25:00,2018-01-26 15:45:00,2018-01-18,logistic partner

In [39]:
late = late[['order_purchase_date','order_delivered_carrier_date','order_delivered_customer_date',
             'order_estimated_delivery_date','fault']]
late

,order_purchase_date,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,fault
20,2017-09-18 14:31:00,2017-10-06 17:50:00,2017-10-09 22:23:00,2017-09-28,seller
25,2018-02-20 23:46:00,2018-02-26 22:25:00,2018-03-21 22:03:00,2018-03-12,logistic partner
35,2018-02-17 15:59:00,2018-02-20 23:03:00,2018-03-20 00:59:00,2018-03-20,logistic partner
41,2017-11-24 21:27:00,2017-12-13 21:14:00,2017-12-28 18:59:00,2017-12-21,logistic partner
57,2018-03-09 14:50:00,2018-03-15 00:31:00,2018-04-03 13:28:00,2018-04-02,logistic partner
...,...,...,...,...,...
99396,2018-08-02 22:46:00,2018-08-15 17:42:00,2018-08-21 00:03:00,2018-08-16,logistic partner
99397,2018-03-13 21:48:00,2018-03-14 19:27:00,2018-04-05 19:59:00,2018-04-02,logistic partner
99423,2017-10-12 20:54:00,2017-10-17 17:04:00,2017-11-21 17:06:00,2017-10-31,logistic partner
99425,2018-03-21 19:47:00,2018-03-22 21:11:00,2018-04-11 00:48:00,2018-04-09,logistic partner
99432,2017-12-20 09:52:00,2017-12-20 20:25:00,2018-01-26 15:45:00,2018-01-18,logistic partner

In [40]:
# Convert the datetime columns to integer

In [41]:
late['order_purchase_date'] = late['order_purchase_date'].apply(lambda x:x.toordinal())
late['order_delivered_carrier_date'] = late['order_delivered_carrier_date'].apply(lambda x:x.toordinal())
late['order_delivered_customer_date'] = late['order_delivered_customer_date'].apply(lambda x:x.toordinal())
late['order_estimated_delivery_date'] = late['order_estimated_delivery_date'].apply(lambda x:x.toordinal())
late

C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\921395993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['order_purchase_date'] = late['order_purchase_date'].apply(lambda x:x.toordinal())
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\921395993.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['order_delivered_carrier_date'] = late['order_delivered_carrier_date'].apply(lambda x:x.toordinal())
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\921395993.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['order_delivered_customer_date'] = late['order_delivered_customer_date'].apply(lambda x:x.toordinal())
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\921395993.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['order_estimated_delivery_date'] = late['order_estimated_delivery_date'].apply(lambda x:x.toordinal())

,order_purchase_date,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,fault
20,736590,736608,736611,736600,seller
25,736745,736751,736774,736765,logistic partner
35,736742,736745,736773,736773,logistic partner
41,736657,736676,736691,736684,logistic partner
57,736762,736768,736787,736786,logistic partner
...,...,...,...,...,...
99396,736908,736921,736927,736922,logistic partner
99397,736766,736767,736789,736786,logistic partner
99423,736614,736619,736654,736633,logistic partner
99425,736774,736775,736795,736793,logistic partner
99432,736683,736683,736720,736712,logistic partner

In [42]:
late['purchase_to_carrier'] = late['order_delivered_carrier_date'] - late['order_purchase_date']
late['carrier_to_customer'] = late['order_delivered_customer_date'] - late['order_delivered_carrier_date']
late = late[['purchase_to_carrier','carrier_to_customer','fault']]
late.fault[late.fault == 'seller'] = 0
late.fault[late.fault == 'logistic partner'] = 1
late

C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['purchase_to_carrier'] = late['order_delivered_carrier_date'] - late['order_purchase_date']
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late['carrier_to_customer'] = late['order_delivered_customer_date'] - late['order_delivered_carrier_date']
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.fault == 'seller'] = 0
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.fault == 'seller'] = 0
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.fault == 'logistic partner'] = 1
C:\Users\kshit\AppData\Local\Temp\ipykernel_10584\3316937701.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  late.fault[late.fault == 'logistic partner'] = 1

       purchase_to_carrier  carrier_to_customer fault
20                      18                    3     0
25                       6                   23     1
35                       3                   28     1
41                      19                   15     1
57                       6                   19     1
...                    ...                  ...   ...
99396                   13                    6     1
99397                    1                   22     1
99423                    5                   35     1
99425                    1                   20     1
99432                    0                   37     1

[7826 rows x 3 columns]

In [60]:
# Loading different binary classification models.

models = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models['Logistic Regression'] = LogisticRegression()

# Support Vector Machines
from sklearn.svm import LinearSVC
models['Support Vector Machines'] = LinearSVC()

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models['Decision Trees'] = DecisionTreeClassifier()

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models['Random Forest'] = RandomForestClassifier()

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
models['Naive Bayes'] = GaussianNB()

# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models['K-Nearest Neighbor'] = KNeighborsClassifier()

In [62]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import accuracy_score, precision_score, recall_score


#split dataset in features and target variable
feature_cols = ['purchase_to_carrier','carrier_to_customer']
X = late[feature_cols] # Features
y = late['fault'] # Target Variables
y=y.astype('int')

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

accuracy, precision, recall = {}, {}, {}

for key in models.keys():
    
    # Fit the classifier
    models[key].fit(X_train, y_train)
    
    # Make predictions
    predictions = models[key].predict(X_test)
    
    # Calculate metrics
    accuracy[key] = accuracy_score(predictions, y_test)
    precision[key] = precision_score(predictions, y_test)
    recall[key] = recall_score(predictions, y_test)
    
results = pd.DataFrame(index=models.keys(), columns=['Accuracy', 'Precision', 'Recall'])
results['Accuracy'] = accuracy.values()
results['Precision'] = precision.values()
results['Recall'] = recall.values()

results

C:\Users\kshit\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

                         Accuracy  Precision    Recall
Logistic Regression      0.962947   0.989130  0.971963
Support Vector Machines  0.963799   0.986866  0.974944
Decision Trees           0.955707   0.978714  0.974301
Random Forest            0.961244   0.985507  0.973602
Naive Bayes              0.942078   0.963768  0.974359
K-Nearest Neighbor       0.961670   0.990036  0.969831